### ISSUE TITLE
An issue with the running of FastqCleaner in Rstudio

### ISSUE THREAD

**Issue by zagrosman** [leandroroser/FastqCleaner#1]
When I launch FastqCleaner in RStudio, the following error would appear in my browser, Do you know how can I solve this problem?

![image](https://user-images.githubusercontent.com/17006122/144634638-3f2a5e00-e6da-4632-970e-c1d9fe164bfc.png)

Listening on http://127.0.0.1:6325
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Error in : Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
  85: stop
  84: FUN
  83: lapply
  82: buildTabset
  81: tabsetPanel_
  80: func
  78: tabsetPanel

And also in my browser:

![image](https://user-images.githubusercontent.com/17006122/144634825-33065dfe-dcb8-4874-bfe7-3063dc139bb2.png)

**Comment by leandroroser** [comment]
Excellent, thanks. Reviewing the issue. Some change in Shiny  is triggering the problem.

**Comment by zagrosman** [comment]
Today I received an email from Leandro and he fixed the problem.  I used the following procedure to run the tool successfully, 

1- First, I removed the formerly installed version through the following command:
``````````````
remove.packages("FastqCleaner")

``````````````

2- Then, devtools package loaded: 
```````````````
library(devtools)
```````````````
3- Next, the installation method given by Leandro was used to re-install the tool:
```````````````
devtools::install_github("https://github.com/leandroroser/FastqCleaner")
```````````````
4- Finally the FastqCleaner was loaded and launched through the following commands:
```````````````
library('FastqCleaner')
launch_fqc()
```````````````

and the software appeared in my web browser. 

![image](https://user-images.githubusercontent.com/17006122/146671675-26ace77a-704d-46e4-968a-cb7ef135779f.png)



For more details interested researchers can see the following link provided by FastqCleaner developers:

```````````````
https://leandroroser.github.io/FastqCleaner/articles/Overview.html

```````````````

Thanks for your support and consideration. 



Sincerely, 


Hassan

**Comment by leandroroser** [comment]
Thank you, Hassan. Can I tag this issue as solved?

**Comment by zagrosman** [comment]
Dear Leandro,

Thanks for your helpful support. I checked the tool in detail and there were no further problems with its installation or launching. Please kindly tag the post as a solved matter.


**_FastqCleaner works clearly._** 


![image](https://user-images.githubusercontent.com/17006122/146686174-5761cb19-5990-4412-9449-8bb749612611.png)


Take care man.

**Comment by leandroroser** [comment]
Excellent! Closing this issue.
